# Generated by Django 5.1.6 on 2025-03-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialist', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
